function feature=features_time(x)
l=length(x);
u=sum(x)/l;%求平均
siga=sqrt(sum((x-u).^2)/(l-1));
PV=max(abs(x));  %峰值
PPV=max(x)-min(x); %峰峰值
AP=sum(abs(x))/l;%平均幅值
RP=(sum(sqrt(abs(x)))/l)^2;%均方根值
RMS=sqrt(sum(x.^2)/l);%有效值
SF=sqrt(sum(x.^2)/l)/(sum(abs(x))/l);%波形因子
IF=max(abs(x))/(sum(abs(x))/l);%脉冲因子
CF=max(abs(x))/sqrt(sum(x.^2)/l);%峰值因子
CLF=max(abs(x))/(sum(sqrt(abs(x)))/l)^2;%裕度因子
SK=sum((x-u).^3)/(l*(siga^3));%歪度因子 
KU=sum((x-u).^4)/(l*(siga^4));%峭度因子
feature=[PV,PPV,AP,RP,RMS,SF,IF,CF,CLF,SK,KU];